-- CREATE DATABASE virtualPet;
USE virtualPet;
CREATE TABLE Pet(
PetID INT UNSIGNED NOT NULL AUTO_INCREMENT,
PetName VARCHAR(50),
FilePath VARCHAR(255),
JsonString VARCHAR(255),
PRIMARY KEY (PetID)
);

CREATE TABLE user(
userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
userName VARCHAR(50),
PetID INT UNSIGNED NOT NULL,
Money FLOAT,
Items VARCHAR(255),
FOREIGN KEY (PetID) REFERENCES Pet(PetID),
PRIMARY KEY(userID)
);